# Generated by Django 4.2.2 on 2023-06-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="")),
                ("ingredients", models.TextField(max_length=500)),
                ("instructions", models.TextField(max_length=1000)),
                ("price", models.FloatField(default=0)),
            ],
        ),
    ]
