# Generated by Django 4.2.2 on 2023-06-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal", name="img", field=models.ImageField(upload_to="meals/"),
        ),
    ]
