# Generated by Django 4.0.7 on 2023-06-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_meal_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='meal',
            name='instructions',
            field=models.TextField(max_length=13000),
        ),
    ]
